server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location /api/households {
    proxy_pass http://household-service:8000;
    proxy_set_header Host $host;
  }

  location /api/tasks {
    proxy_pass http://task-service:8000;
    proxy_set_header Host $host;
  }

  location /api/devices {
    proxy_pass http://device-service:8000;
    proxy_set_header Host $host;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}

