apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - config/app-config.yaml
  - postgres/postgres.yaml
  - postgres/databases.yaml
  - household-service/deployment.yaml
  - task-service/deployment.yaml
  - device-service/deployment.yaml
  - frontend/deployment.yaml
  - config/hpa.yaml

  - alertmanager/deployment.yaml
  - signal-worker/deployment.yaml
  - signal-receiver/deployment.yaml
  - config/signal-scaling.yaml
