apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - config/app-config.yaml
  - postgres/postgres.yaml
  - household-service/deployment.yaml
  - task-service/deployment.yaml
  - device-service/deployment.yaml
  - frontend/deployment.yaml
  - config/hpa.yaml

